# Site
repository: toMySun/toMySun.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Tommi
title: Investor, CEO.
email: tommi.sundqvist@protonmail.com
phone: +358401751981
website: github.com/toMySun/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: promercatoria
github_username:  toASun
stackoverflow_username: ToASun
linkedin_username: tommi-sundqvist-b675471a6


# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  
  Everything IT. Business dev., Lawyer. Dad of 4. Geek.

  <mark>2008</mark> Masters Degree in Business Administration.

  <mark>2008</mark> Started working in Financial Sector. Inter alia Specialist, Service Manager @ Mandatum. Main responsibilities were Main User in new software. Testing Manager.

  <mark>2012</mark> Software development manager and technology start-up investments in private legal office.

  <mark>2018</mark> Masters Degree in Law. Yay!  IT Lawyer, Cum Laude (gpa 5.0) 

  <mark>2012-2019</mark> Entrepreneur. Legal services for businesses in Technology Sector. Manager and CIO in a Legal Firm specialized in financing and investments in new technologies. 
  <mark>2020</mark> Private investor. Studying data sciences further. Writing on legal framework regulating  disruptive technologies. Working on online food delivery applications.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Interested in European regulatory development in IT, taxation on Cryptocurrencies etc. Looking for gamechanger collaboration & groundbreaking projects. Do not hesitate to contact if you like to ask about business law, taxation or regulation. You can contact me if you visit Slush (I'm there every year) or if you have some collaboration in mind. Aside from working on everything about business law in technology sector, I am a investor and visit regularly Estonia mainly due to the start-up landscape in crypto and blockchain technologies.
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
 
  ]
